[theme]
primaryColor = "#14c7dd"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#15171a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

